[package]
name = "day03s"
version = "0.1.0"
authors = ["Minmei"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day03s"
path = "src/day03s.rs"
