[package]
name = "Day03a"
version = "0.1.0"
authors = ["Minmei"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "^0"

[[bin]]
name = "day03a"
path = "src/day03a.rs"
